# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38ec15a4a0d7f52cced38b365f6edb8718b641d18bf56106af7d0998a471f0e95d366f849dacfccf00f0843a1f27ee5427db73d5903b110e7098898f851838d2

test:
  secret_key_base: 91837a7ae3906f5e3b4c4bd2f1e9b3de6ffb4b7fd258839e045b5f4d1af7936472f588608d02f9d5f6efd71ba0fb10c07de5006d3c57cd507c34e69700d83c61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
